# Generated by Django 3.0.8 on 2021-01-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicingredient',
            options={'ordering': ['name']},
        ),
    ]
